spring:
  application:
    name: backend

  config:
    import: optional:file:../.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/memory_calendar
    username: memory_calendar
    password: local_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600