name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Home Server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /srv/memory-calendar

            git fetch origin
            git switch main
            git pull origin main

            docker compose up -d --build

            docker compose ps